name: Test Python Script

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository'yi indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Paketleri kur
        run: pip install -r requirements.txt

      - name: Python scriptini çalıştır
        run: python test.py
